### ISSUE TITLE
node server.js后提示找不到axios模块

### ISSUE THREAD

**Issue by tian0o0** [yxuchen/Music-Player#8]
然后npm install axios -g 安装后提示仍然找不到axios命令，不知道怎么办

**Comment by yxuchen** [comment]
axios不需要全局安装 

npm install axios --save
或者yarn add axios

**Comment by tian0o0** [comment]
我是说在服务器上node server.js的时候，提示找不到`axios`
服务器上需要安装axios吗？

**Comment by yxuchen** [comment]
服务器和你本地类似 所有依赖都要装的 node不也是你现装的。。。。
